#!/usr/bin/env bash
# A 'activate' script is available for both the pkg and git version.
# This is the git version.
REPO=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
make -C "$REPO" build-debug

export PATH="$REPO/target/debug/":$PATH
export PATH=$(find $REPO/examples -maxdepth 1 -mindepth 1 -type d | tr '\n' : ):$PATH
export PATH="$REPO/emulate":$PATH
export PYTHONPATH="$REPO/target/python/:$PYTHONPATH"

export LK_DIR=${LK_DIR:-"$REPO/private"}
export LK_GROUP=${LK_GROUP:-[#:test]}

if [[ ! -v LK_PASS ]]; then
    export LK_PASS=$(lk --init key --no-pubkey --no-enckey --display-pass --password "" --decrypt-cost 0 )
fi

TMP=$(lk e "[0/b/2mini]" argv --data-str $(lk key --no-check --no-enckey))
export PS1="$TMP - ${PS1:-\$}"
echo "LK_DIR = $LK_DIR"
