[patch.crates-io]

[workspace]
members = [
    "crates/*",
    "cli/*",
    "ffi/*",
    "examples/*/*-rs/*"
]


[profile.dev.package.linkspace-argon2-identity]
opt-level = 2
[profile.dev.package.blake3 ]
opt-level = 2



[profile.release]
lto = true