
[target.aarch64-unknown-linux-gnu]
image = "messense/manylinux2014-cross:aarch64"

[target.x86_64-unknown-linux-gnu]
image = "messense/manylinux2014-cross:x86_64"

[target.i686-unknown-linux-gnu]
zig = "2.12"
[target.i686-unknown-linux-musl]
zig = "2.12"
