[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER", # = lld-link
]
[target.aarch64-unknown-linux-gnu]
image = "messense/manylinux2014-cross:aarch64"

[target.x86_64-unknown-linux-gnu]
image = "messense/manylinux2014-cross:x86_64"