#!/bin/bash
set -euo pipefail
source ./activate
lk init

echo "Opening key ${LK_KEYNAME:-me:local}"
export LK_PASS=$(lk key --no-pubkey --no-enckey --display-pass)
export LK_GROUP=[#:test]
export SERVER=testexchange.alinkspace.org:5020
echo "Connecting to $SERVER"
echo Use a different terminal and \'source ./activate\' to try out the examples
exec anyhost.connect.sh 
