[package]
name = "adoto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace=true
pretty = "0.11.3"
serde.workspace = true
serde_json = "1.0.92"
