#!/usr/bin/env bash
# A 'activate' script is available in the source and binary pkg.
# This is the version compatible with the binary pkg.

export PYTHONPATH=$PWD/python
export PATH=$PWD/bin:$PATH
export PATH=$(find $PWD/examples -maxdepth 1 -mindepth 1 -type d | sed -z 's/\n/:/g'):$PATH

export LK_DIR=${LK_DIR:-"$PWD/linkspace"}
export LK_GROUP=${LK_GROUP:-[#:test]}

if [[ ! -v LK_PASS ]]; then
    export LK_PASS=$(lk --init key --no-pubkey --no-enckey --display-pass --password "" --decrypt-cost 0 )
fi

TMP=$(lk key --no-check --no-enckey | lk e --stdin [0/?b/2mini])
export PS1="$TMP - ${PS1:-\$}"
echo "LK_DIR = $LK_DIR"
echo "LK_GROUP = $LK_GROUP"