#!/bin/bash
set -euo pipefail

case "${1:-UNKNOWN}" in
  inspect-tree)
  	  lk --private watch --bare --mode ${2:-tree-desc} --no-new -- "type:1:[b2:00000010]" "${@:3}" | \
     		  lk pktf  "[group:str] [domain:str] [path_len:str] [path:str] [pubkey:str] :: { [create:str] [hash:str] _rx_ }"
      
      ;;
  log)
      lk --private watch --bare --mode log-asc --no-new | lk pktf
      ;;
  blobs-in)
      export FILE=$2
      export CHAN=${3:-default}
      export IN=${4:-$FILE}
      cat "$IN" | lk data | lk --env collect blobs:$LK_GROUP:/[env:CHAN]/[env:FILE] --write db --forward db
      ;;
  blobs-out)
      export FILE=$2
      export CHAN=${3:-default}
      export OUT=${4:-$FILE}
      lk --env watch "blobs:$LK_GROUP:/[env:CHAN]/[env:FILE]" --max 1 | \
          lk --env get-links --rr --forward null --write "file-expr:[env:OUT]:[data]" pause
      ;;
  *)
      echo "No such command $@"
      cat "${BASH_SOURCE[0]}"; exit 1 ;;
esac
