#!/bin/bash
source ./common
lk init
echo "Opening key [@:me:local] - will generate if not yet setup"
export LK_PASS=$(lk key --no-pubkey --no-enckey --display-pass)
export LK_GROUP=[#:test]
export SERVER=83.172.162.31:5020
exec ./exchange/anyhost/connect.sh
