[package]
name = "linkspace-cli"
version = "0.1.3"
edition = "2021"

authors = ["Azon <AntonSol919@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/AntonSol919/linkspace"
categories = ["command-line-utilities","database","network-programming","asynchronous"]

[[bin]]
name = "lk"
path = "src/main.rs"

[dependencies]
anyhow = "*"
liblinkspace = { path = "../../crates/liblinkspace" }
linkspace-common = { path = "../../crates/common" }
serde_json = "1.0.82"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }